INSERT INTO `photos`(`title`, `url`, `description`, `created_at`, `visible`) VALUES ('foto 1','/img/capolavoro1.jpg','Foto generata da intelligenza artificiale', '2023-07-06 12:07:00', true)
INSERT INTO `photos`(`title`, `url`, `description`, `created_at`, `visible`) VALUES ('foto 2','/img/capolavoro2.jpg','Foto generata da intelligenza artificiale', '2023-07-06 12:07:00', true)
INSERT INTO `photos`(`title`, `url`, `description`, `created_at`, `visible`) VALUES ('foto 3','/img/capolavoro3.jpg','Foto generata da intelligenza artificiale', '2023-07-06 12:07:00', true)
INSERT INTO `photos`(`title`, `url`, `description`, `created_at`, `visible`) VALUES ('foto 4','/img/capolavoro4.jpg','Foto generata da intelligenza artificiale', '2023-07-06 12:07:00', true)
INSERT INTO `photos`(`title`, `url`, `description`, `created_at`, `visible`) VALUES ('foto 5','/img/capolavoro5.jpg','Foto generata da intelligenza artificiale', '2023-07-06 12:07:00', true)

INSERT INTO `categories`(`name`) VALUES ('Natura')
INSERT INTO `categories`(`name`) VALUES ('Mare')
INSERT INTO `categories`(`name`) VALUES ('Montagna')
INSERT INTO `categories`(`name`) VALUES ('Città')
INSERT INTO `categories`(`name`) VALUES ('Monumenti')

INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('1','1')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('3','1')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('1','2')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('2','2')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('1','3')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('2','3')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('4','3')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('4','4')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('5','4')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('1','5')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('3','5')
INSERT INTO `category_photo`(`category_id`, `photo_id`) VALUES ('4','5')

